# Generated by Django 4.2.13 on 2024-05-17 14:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('FF', 'Foxglove Field'), ('EE', 'Elderberry End'), ('MM', 'Marigold Mews'), ('PP', 'Primrose Path'), ('WW', 'Windrush Way'), ('BB', 'Buckleberry Bend'), ('AA', 'Arkenstone Avenue'), ('RR', 'Redleaf Rise'), ('OO', 'Old Oak End'), ('SS', 'Shirebrook Springs'), ('HH', 'Harvest Hollow'), ('CC', 'Cobblestone Crossing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(choices=[('other', 'Other'), ('gardening', 'Gardening'), ('tech', 'Tech'), ('kids', 'Kids'), ('leisure', 'Leisure'), ('pets', 'Pets'), ('borrow', 'Borrow'), ('carpool', 'Carpool'), ('repairs', 'Repairs')], max_length=10),
        ),
    ]
