# Generated by Django 4.2.13 on 2024-05-20 09:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_location_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="happyhelping/",
            ),
        ),
    ]
