# Generated by Django 4.2.13 on 2024-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_post_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bookmarks",
        ),
        migrations.AddField(
            model_name="post",
            name="contact_details",
            field=models.CharField(default="n.a.", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Evenings", "Evenings"),
                    ("Weekends", "Weekends"),
                    ("Generally Available", "Generally Available"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
