# Generated by Django 4.2.13 on 2024-05-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_remove_post_bookmarks_post_contact_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tools_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I Have the Necessary Tools", "I Have the Necessary Tools"),
                    (
                        "Tools Required - which I Do Not Have",
                        "Tools Required - which I Do Not Have",
                    ),
                    ("No Tools Required", "No Tools Required"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
