# Generated by Django 4.2.13 on 2024-05-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_post_status_alter_post_tools_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_subcategory",
                to="board.subcategory",
            ),
        ),
    ]
